package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/j-core/jcore-cpu/decode/gen-go/internal/variants"
)

// emitMakeFragment renders variants.toml as a GNU Make fragment. Make cannot
// parse TOML, so Makefile.inc -includes this generated file and lets Make's
// remake-included-files rule build it on demand.
func emitMakeFragment(tomlPath string) (string, error) {
	m, err := variants.Load(tomlPath)
	if err != nil {
		return "", err
	}
	names := variants.Names(m)
	var b strings.Builder
	b.WriteString("# GENERATED by `cpugen variants -format=make` from variants.toml.\n")
	b.WriteString("# Do not edit. Edit variants.toml instead.\n")
	fmt.Fprintf(&b, "CPU_VARIANT_ALL := %s\n", strings.Join(names, " "))
	for _, n := range names {
		v := m[n]
		gk := make([]string, 0, len(v.Generics))
		for k := range v.Generics {
			gk = append(gk, k)
		}
		sort.Strings(gk)
		pairs := make([]string, 0, len(gk))
		for _, k := range gk {
			pairs = append(pairs, k+"="+v.Generics[k])
		}
		fmt.Fprintf(&b, "CPU_VARIANT_%s_GENERICS := %s\n", n, strings.Join(pairs, " "))
		fmt.Fprintf(&b, "CPU_VARIANT_%s_OVERLAY := %s\n", n, v.Overlay)
		fmt.Fprintf(&b, "CPU_VARIANT_%s_EXTRA_FILES := %s\n", n, strings.Join(v.ExtraFiles, " "))
		fmt.Fprintf(&b, "CPU_VARIANT_%s_CONFIG_FILE := %s\n", n, v.ConfigFile)
	}
	return b.String(), nil
}

func runVariants(args []string) int {
	fs := flag.NewFlagSet("variants", flag.ExitOnError)
	format := fs.String("format", "", "output format (required: make)")
	variantsPath := fs.String("variants", "../../variants.toml", "path to variants.toml")
	outPath := fs.String("o", "", "output file; if empty, write to stdout")
	fs.Parse(args) //nolint:errcheck

	if *format != "make" {
		fmt.Fprintf(os.Stderr, "variants: -format=%q is invalid; only 'make' is supported\n", *format)
		return 1
	}

	fragment, err := emitMakeFragment(*variantsPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "variants: %v\n", err)
		return 1
	}

	if *outPath == "" {
		fmt.Print(fragment)
		return 0
	}

	if err := os.WriteFile(*outPath, []byte(fragment), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "variants: write: %v\n", err)
		return 1
	}

	return 0
}
