package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/j-core/jcore-cpu/decode/gen-go/internal/spec"
)

// defaultBlock is the global defaults written into every spec/*.toml file.
var defaultBlock = spec.Defaults{PC: "INC", IfIssue: "NO", SR: "HOLD"}

// emitTOML writes one TOML file per category under outDir. Instructions
// within a file are sorted by Opcode for diff stability.
func emitTOML(outDir string, byCategory map[string][]spec.Instr) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	for cat, instrs := range byCategory {
		sort.Slice(instrs, func(i, j int) bool {
			return instrs[i].Opcode < instrs[j].Opcode
		})
		file := spec.File{Defaults: defaultBlock, Instrs: instrs}
		var buf strings.Builder
		buf.WriteString("# Generated by cmd/csv2toml from SH-2 Instruction Set.csv\n")
		buf.WriteString("# Edit this file directly; the CSV is archival.\n\n")
		enc := toml.NewEncoder(&buf)
		enc.Indent = "  "
		if err := enc.Encode(file); err != nil {
			return fmt.Errorf("encode %s: %w", cat, err)
		}
		path := filepath.Join(outDir, cat+".toml")
		if err := os.WriteFile(path, []byte(buf.String()), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}
