#!/usr/bin/env bash
# VSG (VHDL Style Guide) lint entry point — single source of the in-scope
# file list + invocation, used by both CI (vhdl-lint.yml) and local runs.
#
# Scope (see .superpowers/sdd/task-A-brief.md Global Constraints):
#   - EXCLUDED entirely: the 10 Go-generated decode/decode*.vhd files.
#   - .vhm-derived .vhd: preprocessed fresh from the matching .vhm via v2p,
#     so lint reflects the current .vhm source (source of truth), not
#     whatever .vhd happens to be checked in.
#   - Everything else tracked *.vhd is hand-written and linted as-is.
#
# Usage: scripts/vhdl-lint.sh [--fix]
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

TOOLS_DIR="${TOOLS_DIR:-/home/cedric/work/jcore/jcore-soc/tools}"
JCORE_SOC="${JCORE_SOC:-/home/cedric/work/jcore/jcore-soc}"

# Go-generated decoder outputs: never linted (regenerated by cpugen, not
# hand-formatted; Phases B/C do not touch these).
EXCLUDE_GENERATED=(
  "decode/decode.vhd"
  "decode/decode_body.vhd"
  "decode/decode_pkg.vhd"
  "decode/decode_table.vhd"
  "decode/decode_table_direct.vhd"
  "decode/decode_table_direct_config.vhd"
  "decode/decode_table_rom.vhd"
  "decode/decode_table_rom_config.vhd"
  "decode/decode_table_simple.vhd"
  "decode/decode_table_simple_config.vhd"
)

# .vhm-derived .vhd: the .vhm is the source of truth; regenerate the .vhd
# via v2p before linting so we lint what the .vhm currently produces.
VHM_STEMS=(
  "core/datapath"
  "core/mult"
  "decode/decode_core"
  "cache/dcache_ccl"
  "cache/dcache_mcl"
  "cache/icache_ccl"
  "cache/icache_mcl"
  "cache/icache_modereg"
  "cache/icache_modereg_wsbu"
  "sim/timeout_cnt"
)

echo "Preprocessing .vhm -> .vhd via v2p ..." >&2
for stem in "${VHM_STEMS[@]}"; do
  LD_LIBRARY_PATH='' perl "$JCORE_SOC/tools/v2p" < "$stem.vhm" > "$stem.vhd"
done

# The .vhm-derived .vhd we add explicitly (regenerated above). Most are
# untracked build artifacts, so git ls-files would miss them; and where one
# IS tracked (core/datapath.vhd) we must not list it twice. So exclude both
# the generated set and the vhm-derived set from the tracked scan, then append
# the vhm-derived .vhd back explicitly.
VHM_DERIVED=()
for stem in "${VHM_STEMS[@]}"; do VHM_DERIVED+=("$stem.vhd"); done

is_excluded() {
  local f="$1"
  for e in "${EXCLUDE_GENERATED[@]}" "${VHM_DERIVED[@]}"; do
    [[ "$f" == "$e" ]] && return 0
  done
  return 1
}

FILES=()
while IFS= read -r f; do
  is_excluded "$f" && continue
  FILES+=("$f")
done < <(git ls-files '*.vhd' | sort)

# Append the regenerated .vhm-derived .vhd (source of truth = the .vhm).
FILES+=("${VHM_DERIVED[@]}")

echo "Linting ${#FILES[@]} files (hand-written tracked .vhd + ${#VHM_DERIVED[@]} .vhm-derived; excluded ${#EXCLUDE_GENERATED[@]} Go-generated decode files)" >&2

VSG_ARGS=(-c vsg_config.yaml -f "${FILES[@]}")
if [[ "${1:-}" == "--fix" ]]; then
  VSG_ARGS+=(--fix)
fi

set +e
OUTPUT="$(vsg "${VSG_ARGS[@]}" 2>&1)"
STATUS=$?
set -e

echo "$OUTPUT"

# VSG prints one summary block per file; sum them for the grand total.
TOTAL=$(echo "$OUTPUT" | grep -oE 'Total Violations:[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | paste -sd+ | bc)
echo "Total violations: ${TOTAL:-0}"

exit "$STATUS"
